[build]
command = "npm run build"
functions = "netlify/functions"
publish = "public"

[dev]
command = "npm start"

[[redirects]]
from = "/search/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
